import{app,BrowserWindow,dialog,ipcMain}from'electron';import path from'node:path';import{z}from'zod';import{LifeboatDatabase}from'../database';import{authenticate,inventory,authFor}from'../google';import{tokens}from'../keychain';import{exportReports}from'../report';import{validateAccountRoles}from'../security';import{copyArgs,findRclone,listRemotes,parseProgress,RcloneProcess,remoteAbout,testDestination,validateDestination,validateRemote,checkArgs}from'../rclone';import{discoverDrive,sharedAudit}from'../drive';import type{AccountRole}from'../types';
import{aggregateVerification,validateSample}from'../verification';
let win:BrowserWindow|null=null,db:LifeboatDatabase,clientPath='',activeJob:string|null=null,progress:any={};const runner=new RcloneProcess();
const settingsSchema=z.object({deadline:z.string(),dryRun:z.boolean(),sourceEmail:z.string().email(),destinationEmail:z.string().email(),fallbackEmail:z.string().email()});const defaults={deadline:'2026-08-03',dryRun:true,sourceEmail:'joshua.parris@cornerstone.edu.au',destinationEmail:'joshualparris@gmail.com',fallbackEmail:'joshparriscornerstone@gmail.com'};
function dashboard(){return{settings:db.setting('settings',defaults),accounts:db.accounts(),latestInventory:db.latestInventory(),queue:db.queueCounts(),drive:{config:db.setting('driveConfig',{}),rclone:db.setting('rcloneInfo',null),stats:db.driveStats(),jobs:db.jobs(),running:runner.running(),progress}}}
function createWindow(){win=new BrowserWindow({width:1360,height:900,minWidth:980,minHeight:680,backgroundColor:'#f4f1e8',webPreferences:{preload:path.join(__dirname,'../preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true}});if(process.env.VITE_DEV_SERVER_URL)win.loadURL(process.env.VITE_DEV_SERVER_URL);else win.loadFile(path.join(__dirname,'../../dist/index.html'))}
app.whenReady().then(()=>{db=new LifeboatDatabase(path.join(app.getPath('userData'),'lifeboat.db'));createWindow()});app.on('before-quit',()=>runner.pause());app.on('window-all-closed',()=>{db?.close();if(process.platform!=='darwin')app.quit()});
ipcMain.handle('dashboard',()=>dashboard());ipcMain.handle('pick-client',async()=>{const r=await dialog.showOpenDialog(win!,{title:'Select Google OAuth desktop client',properties:['openFile'],filters:[{name:'JSON',extensions:['json']}]});if(r.canceled)return false;clientPath=r.filePaths[0];db.setSetting('clientPath',clientPath);return true});
ipcMain.handle('connect',async(_e,role:AccountRole)=>{if(!['source','destination'].includes(role))throw new Error('Invalid account role');const p=clientPath||db.setting('clientPath','');if(!p)throw new Error('Select client_secret.json first');const acct=await authenticate(role,p),others=db.accounts().filter(a=>a.role!==role),set=dashboard().settings;if(role==='source'&&others[0])validateAccountRoles(acct.email,others[0].email,[set.destinationEmail,set.fallbackEmail]);if(role==='destination'&&others[0])validateAccountRoles(others[0].email,acct.email,[set.destinationEmail,set.fallbackEmail]);db.saveAccount(acct);return dashboard()});
ipcMain.handle('disconnect',async(_e,role:AccountRole)=>{if(!['source','destination'].includes(role))throw new Error('Invalid account role');try{const auth=await authFor(role);if(auth.credentials.access_token)await auth.revokeToken(auth.credentials.access_token)}catch{}await tokens.remove(role);db.removeAccount(role);return dashboard()});ipcMain.handle('save-settings',(_e,v)=>{const s=settingsSchema.parse(v),a=db.accounts(),source=a.find(x=>x.role==='source'),dest=a.find(x=>x.role==='destination');if(source&&dest)validateAccountRoles(source.email,dest.email,[s.destinationEmail,s.fallbackEmail]);db.setSetting('settings',s);return dashboard()});
ipcMain.handle('run-inventory',async()=>{const source=db.accounts().find(a=>a.role==='source');if(!source)throw new Error('Connect the source account first');const snap=await inventory(source.email);db.saveInventory(snap);return dashboard()});ipcMain.handle('export-reports',async()=>{const snap=db.latestInventory();if(!snap)throw new Error('Run an inventory first');const r=await dialog.showOpenDialog(win!,{title:'Choose report folder',properties:['openDirectory','createDirectory']});if(r.canceled)return null;return exportReports(r.filePaths[0],snap,db.exportRows(),{drive:dashboard().drive,manifest:db.drivePage(0,100000),shared:sharedAudit(db.drivePage(0,100000,true),dashboard().settings.destinationEmail)} as any)});
ipcMain.handle('rclone-detect',async()=>{let found=findRclone(db.setting('rclonePath',''));if(!found){const r=await dialog.showOpenDialog(win!,{title:'Select rclone executable',properties:['openFile']});if(r.canceled)return dashboard();found=findRclone(r.filePaths[0])}if(!found)throw new Error('rclone was not found or did not pass “rclone version”');const info={...found,remotes:listRemotes(found.path)};db.setSetting('rclonePath',found.path);db.setSetting('rcloneInfo',info);return dashboard()});
ipcMain.handle('rclone-about',(_e,remote:string)=>{const info=db.setting<any>('rcloneInfo',null);if(!info)throw new Error('Detect rclone first');return remoteAbout(info.path,validateRemote(remote))});
ipcMain.handle('drive-set-remote',(_e,remote:string)=>{const info=db.setting<any>('rcloneInfo',null);if(!info?.remotes?.includes(remote))throw new Error('Select a configured rclone remote');remoteAbout(info.path,remote);db.setSetting('driveConfig',{...db.setting('driveConfig',{}),remote});return dashboard()});
ipcMain.handle('drive-pick-destination',async()=>{const r=await dialog.showOpenDialog(win!,{title:'Choose local or NAS backup destination',properties:['openDirectory','createDirectory']});if(r.canceled)return dashboard();const tested=await testDestination(r.filePaths[0]);db.setSetting('driveConfig',{...db.setting('driveConfig',{}),destination:tested.path,freeBytes:tested.freeBytes,totalBytes:tested.totalBytes});return dashboard()});
ipcMain.handle('drive-test-destination',async(_e,destination:string)=>{const tested=await testDestination(destination);db.setSetting('driveConfig',{...db.setting('driveConfig',{}),destination:tested.path,freeBytes:tested.freeBytes,totalBytes:tested.totalBytes});return dashboard()});
ipcMain.handle('drive-discover',async()=>{const source=db.accounts().find(a=>a.role==='source');if(!source)throw new Error('Connect the source account first');await discoverDrive(db,false,n=>{progress={operation:'Discovering Drive',files:n};win?.webContents.send('drive-progress',progress)});return dashboard()});
ipcMain.handle('drive-page',(_e,o=0,l=100,shared=false)=>shared?sharedAudit(db.drivePage(o,l,true),dashboard().settings.destinationEmail):db.drivePage(o,l,false));
ipcMain.handle('drive-start',async(_e,input:{remote:string;destination:string})=>{const source=db.accounts().find(a=>a.role==='source');if(!source)throw new Error('Connect source first');const info=db.setting<any>('rcloneInfo',null);if(!info)throw new Error('Detect rclone first');validateRemote(input.remote);const destination=validateDestination(input.destination);const confirm=await dialog.showMessageBox(win!,{type:'warning',buttons:['Cancel','Start read-only source backup'],defaultId:0,cancelId:0,title:'Confirm Drive backup',message:`Copy from ${source.email} via ${input.remote}:`,detail:`Destination: ${destination}\n\nThis uses rclone copy and never deletes source or destination files.`});if(confirm.response!==1)return dashboard();const args=copyArgs(input.remote,destination),id=db.startJob({type:'drive_backup_copy',remote:input.remote,destination,rclonePath:info.path,version:info.version,args});activeJob=id;progress={bytes:0,totalBytes:0,files:0,checks:0,errors:0,speed:'—',eta:'—',current:'Starting'};runner.start(info.path,args,{line(line){progress=parseProgress(line,progress);db.log(id,line);db.updateJob(id,'running',progress);win?.webContents.send('drive-progress',progress)},exit(code,signal){const paused=signal==='SIGTERM';if(code===0)db.markDriveCopyComplete();db.updateJob(id,paused?'paused':code===0?'complete':'failed',progress,code===0?undefined:`rclone exited ${code??signal}`);activeJob=null;win?.webContents.send('drive-progress',progress)}});return dashboard()});
ipcMain.handle('drive-pause',()=>{if(!activeJob)return dashboard();runner.pause();return dashboard()});
ipcMain.handle('drive-verify',async(_e,input:{remote:string;destination:string})=>{if(runner.running())throw new Error('Pause or finish the backup before verification');const info=db.setting<any>('rcloneInfo',null);if(!info)throw new Error('Detect rclone first');const args=checkArgs(input.remote,input.destination),id=db.startJob({type:'drive_backup_verify',remote:input.remote,destination:input.destination,rclonePath:info.path,version:info.version,args});activeJob=id;progress={operation:'Verification',errors:0};runner.start(info.path,args,{line(line){db.log(id,line);if(line.startsWith('!')||line.startsWith('*'))progress.errors=(progress.errors??0)+1;progress.current=line.slice(0,160);db.updateJob(id,'verifying',progress);win?.webContents.send('drive-progress',progress)},async exit(code){const stats=db.driveStats(),all=db.drivePage(0,100000)as any[],rows=all.filter(x=>!x.is_folder&&x.relative_path).slice(0,20),samples=await Promise.all(rows.map(x=>validateSample(path.join(input.destination,'Cornerstone-Lifeboat','drive',x.relative_path),x.size))),unsupported=all.filter(x=>x.is_native&&!x.export_extension).length,result=aggregateVerification({rcloneExitCode:code,discrepancies:progress.errors??0,failed:stats.failed??0,unsupported,samples});if(result.status!=='incomplete')db.markDriveVerified('rclone-check-download');db.updateJob(id,result.status,progress,result.status==='verified'?undefined:'Verification has discrepancies or documented limitations',{...result,manifest:stats,limitations:['Google-native exports cannot match source checksums','Shared externally-owned items may become inaccessible']});activeJob=null}});return dashboard()});
