import{createHash,randomUUID}from'node:crypto';
import{mkdir,rename,writeFile}from'node:fs/promises';
import path from'node:path';
import{google,calendar_v3}from'googleapis';
import type{LifeboatDatabase}from'./database';
import{authFor}from'./google';
import{redact}from'./security';
const hash=(v:unknown)=>createHash('sha256').update(String(v??'')).digest('hex');
export const safeCalendarName=(s:string)=>`Cornerstone Import/${s.normalize('NFKC').replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,180)||'Calendar'}`;
export function writableEvent(e:calendar_v3.Schema$Event){return{summary:e.summary,description:e.description,location:e.location,start:e.start,end:e.end,recurrence:e.recurrence,transparency:e.transparency,visibility:e.visibility,status:e.status==='cancelled'?undefined:e.status,reminders:e.reminders,extendedProperties:e.extendedProperties,attachments:e.attachments?.map(a=>({fileUrl:a.fileUrl,title:a.title,mimeType:a.mimeType,iconLink:a.iconLink})),source:e.source,conferenceData:e.conferenceData};}
export function eventFingerprint(e:any){return hash(JSON.stringify({s:e.summary??'',a:e.start??{},z:e.end??{},r:e.recurrence??[],l:e.location??''}))}
async function calendars(api:calendar_v3.Calendar){const out:calendar_v3.Schema$CalendarListEntry[]=[];let pageToken:string|undefined;do{const r=await api.calendarList.list({maxResults:250,pageToken});out.push(...(r.data.items??[]));pageToken=r.data.nextPageToken??undefined}while(pageToken);return out}
export async function inventoryCalendars(db:LifeboatDatabase,sourceSubject:string,destinationSubject:string,progress?:(x:any)=>void){const api=google.calendar({version:'v3',auth:await authFor('source')}),runId=randomUUID(),now=new Date().toISOString();db.phaseRun('INSERT INTO calendar_runs VALUES(?,?,?,?,?,?,?)',runId,sourceSubject,destinationSubject,'running',now,null,null);let eventCount=0,calendarCount=0;for(const c of await calendars(api)){if(!c.id)continue;calendarCount++;db.phaseRun('INSERT OR IGNORE INTO calendar_map VALUES(?,?,?,?,?,?)',sourceSubject,destinationSubject,c.id,c.summaryOverride??c.summary??'Calendar',null,'discovered');let token:string|undefined;do{const r=await api.events.list({calendarId:c.id,maxResults:2500,pageToken:token,singleEvents:false,showDeleted:false});for(const e of r.data.items??[]){if(!e.id||!e.start||!e.end)continue;db.phaseRun(`INSERT OR IGNORE INTO calendar_events(id,run_id,source_subject,destination_subject,source_calendar_id,source_event_id,ical_uid,summary_hash,start_json,end_json,recurrence_json,status)VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`,randomUUID(),runId,sourceSubject,destinationSubject,c.id,e.id,e.iCalUID??null,hash(e.summary),JSON.stringify(e.start),JSON.stringify(e.end),JSON.stringify(e.recurrence??[]),'discovered');eventCount++}token=r.data.nextPageToken??undefined;progress?.({operation:'Calendar inventory',calendars:calendarCount,events:eventCount})}while(token)}db.phaseRun("UPDATE calendar_runs SET status='inventory-complete',completed_at=? WHERE id=?",new Date().toISOString(),runId);return{runId,calendars:calendarCount,events:eventCount}}
export async function runCalendars(db:LifeboatDatabase,sourceSubject:string,destinationSubject:string,progress?:(x:any)=>void){const source=google.calendar({version:'v3',auth:await authFor('source')}),dest=google.calendar({version:'v3',auth:await authFor('destination')}),existing=await calendars(dest);for(const m of db.phaseAll('SELECT * FROM calendar_map WHERE source_subject=? AND destination_subject=?',sourceSubject,destinationSubject)){try{let id=m.destination_calendar_id||existing.find(c=>c.summary===safeCalendarName(m.source_name))?.id;if(!id)id=(await dest.calendars.insert({requestBody:{summary:safeCalendarName(m.source_name),timeZone:'Australia/Sydney'}})).data.id!;db.phaseRun("UPDATE calendar_map SET destination_calendar_id=?,status='mapped' WHERE source_subject=? AND destination_subject=? AND source_calendar_id=?",id,sourceSubject,destinationSubject,m.source_calendar_id)}catch(e){db.phaseRun("UPDATE calendar_map SET status='failed' WHERE source_subject=? AND destination_subject=? AND source_calendar_id=?",sourceSubject,destinationSubject,m.source_calendar_id)}}let copied=0,verified=0,failed=0;for(const row of db.phaseAll("SELECT e.*,m.destination_calendar_id mapped_calendar FROM calendar_events e JOIN calendar_map m ON m.source_subject=e.source_subject AND m.destination_subject=e.destination_subject AND m.source_calendar_id=e.source_calendar_id WHERE e.source_subject=? AND e.destination_subject=? AND e.status IN ('discovered','failed-retryable')",sourceSubject,destinationSubject)){if(!row.mapped_calendar){failed++;continue}db.phaseRun("UPDATE calendar_events SET status='copying',attempts=attempts+1 WHERE id=?",row.id);try{const e=(await source.events.get({calendarId:row.source_calendar_id,eventId:row.source_event_id})).data;let created=(await dest.events.import({calendarId:row.mapped_calendar,conferenceDataVersion:1,supportsAttachments:true,requestBody:writableEvent(e)})).data;db.phaseRun("UPDATE calendar_events SET destination_calendar_id=?,destination_event_id=?,status='copied' WHERE id=?",row.mapped_calendar,created.id,row.id);copied++;created=(await dest.events.get({calendarId:row.mapped_calendar,eventId:created.id!})).data;const ok=eventFingerprint(e)===eventFingerprint(created);db.phaseRun("UPDATE calendar_events SET status=?,verification_status=? WHERE id=?",ok?'verified':'manual-action-required',ok?'verified':'mismatch',row.id);if(ok)verified++}catch(e){failed++;db.phaseRun("UPDATE calendar_events SET status='failed-retryable',last_error=? WHERE id=?",redact(e).slice(0,500),row.id)}progress?.({operation:'Migrating calendars',copied,verified,failed})}return{copied,verified,failed}}
export function calendarStats(db:LifeboatDatabase){return db.phaseGet(`SELECT count(*) discovered,sum(destination_event_id IS NOT NULL) copied,sum(status='verified') verified,sum(recurrence_json!='[]') recurring,sum(status LIKE 'failed%') failed FROM calendar_events`)??{}}
export async function verifyCalendarsDestinationOnly(db:LifeboatDatabase,sourceSubject:string,destinationSubject:string){const api=google.calendar({version:'v3',auth:await authFor('destination')});let verified=0,failed=0;for(const r of db.phaseAll('SELECT * FROM calendar_events WHERE source_subject=? AND destination_subject=? AND destination_event_id IS NOT NULL',sourceSubject,destinationSubject))try{const e=(await api.events.get({calendarId:r.destination_calendar_id,eventId:r.destination_event_id})).data,ok=hash(e.summary)===r.summary_hash&&JSON.stringify(e.start)===r.start_json&&JSON.stringify(e.end)===r.end_json&&JSON.stringify(e.recurrence??[])===r.recurrence_json;db.phaseRun("UPDATE calendar_events SET status=?,verification_status=? WHERE id=?",ok?'verified':'manual-action-required',ok?'destination-only-verified':'destination-only-mismatch',r.id);ok?verified++:failed++}catch{failed++;db.phaseRun("UPDATE calendar_events SET verification_status='destination-only-missing' WHERE id=?",r.id)}return{verified,failed}}
const esc=(v:unknown)=>String(v??'').replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/[,;]/g,m=>`\\${m}`),dt=(v:any)=>v?.dateTime?.replace(/[-:]/g,'').replace(/\.\d{3}/,'')??v?.date?.replace(/-/g,'');
export async function exportCalendars(dir:string){const api=google.calendar({version:'v3',auth:await authFor('source')});await mkdir(dir,{recursive:true});const stamp=new Date().toISOString().replace(/[:.]/g,'-'),files:string[]=[];for(const c of await calendars(api)){if(!c.id)continue;const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Cornerstone Lifeboat//EN',`X-WR-CALNAME:${esc(c.summary)}`];let token:string|undefined;do{const r=await api.events.list({calendarId:c.id,maxResults:2500,pageToken:token,singleEvents:false,showDeleted:false});for(const e of r.data.items??[]){if(!e.start||!e.end)continue;lines.push('BEGIN:VEVENT',`UID:${esc(e.iCalUID??e.id)}`,`SUMMARY:${esc(e.summary)}`,`DTSTART:${dt(e.start)}`,`DTEND:${dt(e.end)}`,...(e.recurrence??[]),`DESCRIPTION:${esc(e.description)}`,'END:VEVENT')}token=r.data.nextPageToken??undefined}while(token);lines.push('END:VCALENDAR','');const target=path.join(dir,`cornerstone-calendar-${hash(c.id).slice(0,10)}-${stamp}.ics`),tmp=`${target}.tmp`;await writeFile(tmp,lines.join('\r\n'),{flag:'wx'});await rename(tmp,target);files.push(target)}return files}
