import { google } from 'googleapis';
import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { shell } from 'electron';
import { z } from 'zod';
import { tokens } from './keychain';
import { redact } from './security';
import type { AccountRole, AccountSummary, InventorySnapshot } from './types';

const ClientFile=z.object({installed:z.object({client_id:z.string(),client_secret:z.string(),redirect_uris:z.array(z.string()).optional()})});
export const SOURCE_SCOPES=['openid','email','https://www.googleapis.com/auth/gmail.readonly','https://www.googleapis.com/auth/drive.readonly','https://www.googleapis.com/auth/contacts.readonly','https://www.googleapis.com/auth/contacts.other.readonly','https://www.googleapis.com/auth/calendar.readonly'];
export const DESTINATION_SCOPES=['openid','email','https://www.googleapis.com/auth/gmail.labels','https://www.googleapis.com/auth/gmail.insert','https://www.googleapis.com/auth/drive.file','https://www.googleapis.com/auth/contacts','https://www.googleapis.com/auth/calendar.app.created'];

async function clientConfig(path:string){ const parsed=ClientFile.safeParse(JSON.parse(await readFile(path,'utf8'))); if(!parsed.success)throw new Error('This is not a valid Google OAuth desktop client file'); return parsed.data.installed; }
export async function authenticate(role:AccountRole,path:string):Promise<AccountSummary>{
  const cfg=await clientConfig(path); const server=createServer(); await new Promise<void>((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',()=>resolve());});
  const addr=server.address(); if(!addr||typeof addr==='string')throw new Error('Could not start local OAuth callback'); const redirect=`http://127.0.0.1:${addr.port}/oauth2callback`; const oauth=new google.auth.OAuth2(cfg.client_id,cfg.client_secret,redirect); const state=randomUUID(); const scopes=role==='source'?SOURCE_SCOPES:DESTINATION_SCOPES;
  const codePromise=new Promise<string>((resolve,reject)=>{ const timeout=setTimeout(()=>reject(new Error('OAuth timed out')),180000); server.on('request',(req,res)=>{try{const u=new URL(req.url??'',redirect);if(u.pathname!='/oauth2callback')return;if(u.searchParams.get('state')!==state)throw new Error('OAuth state mismatch');const code=u.searchParams.get('code');if(!code)throw new Error(u.searchParams.get('error')??'No authorization code');res.end('Cornerstone Lifeboat connected. You can close this tab.');clearTimeout(timeout);resolve(code);}catch(e){res.statusCode=400;res.end('Authorization failed.');reject(e);}finally{server.close();}});});
  await shell.openExternal(oauth.generateAuthUrl({access_type:'offline',prompt:'consent',scope:scopes,state,include_granted_scopes:true})); const code=await codePromise; const {tokens:creds}=await oauth.getToken(code); oauth.setCredentials(creds); const info=await google.oauth2({version:'v2',auth:oauth}).userinfo.get(); if(!info.data.email)throw new Error('Google did not return a verified email'); await tokens.set(role,{credentials:creds,clientId:cfg.client_id,clientSecret:cfg.client_secret}); return {role,email:info.data.email.toLowerCase(),scopes:(creds.scope??scopes.join(' ')).split(' '),connectedAt:new Date().toISOString()};
}
export async function authFor(role:AccountRole){const saved=await tokens.get(role);if(!saved)throw new Error(`${role} account is not connected`);const auth=new google.auth.OAuth2(saved.clientId,saved.clientSecret);auth.setCredentials(saved.credentials);return auth;}

export async function inventory(email:string):Promise<InventorySnapshot>{
 const auth=await authFor('source'), errors:InventorySnapshot['errors']=[]; const snap:InventorySnapshot={runId:randomUUID(),createdAt:new Date().toISOString(),account:email,gmail:{messages:0,threads:0,labels:[]},drive:{usageBytes:0,limitBytes:null,files:0,folders:0,googleNative:0,owned:0,shared:0,bytes:0},contacts:{contacts:0,groups:0,otherContacts:null},calendar:{calendars:0,owned:0,shared:0,events:0,recurring:0,future:0},errors};
 try{const api=google.gmail({version:'v1',auth});const profile=await api.users.getProfile({userId:'me'});snap.gmail.messages=profile.data.messagesTotal??0;snap.gmail.threads=profile.data.threadsTotal??0;const labels=await api.users.labels.list({userId:'me'});for(const l of labels.data.labels??[]){if(!l.id)continue;const full=await api.users.labels.get({userId:'me',id:l.id});snap.gmail.labels.push({id:l.id,name:l.name??l.id,messages:full.data.messagesTotal??0,threads:full.data.threadsTotal??0});}}catch(e){errors.push({module:'gmail',message:redact(e)});}
 try{const api=google.drive({version:'v3',auth});const about=await api.about.get({fields:'storageQuota'});snap.drive.usageBytes=Number(about.data.storageQuota?.usage??0);snap.drive.limitBytes=about.data.storageQuota?.limit?Number(about.data.storageQuota.limit):null;let pageToken:string|undefined;do{const r=await api.files.list({pageSize:1000,pageToken,q:'trashed = false',fields:'nextPageToken,files(id,mimeType,size,ownedByMe,parents)',spaces:'drive'});for(const f of r.data.files??[]){snap.drive.files++;if(f.mimeType==='application/vnd.google-apps.folder')snap.drive.folders++;if(f.mimeType?.startsWith('application/vnd.google-apps.')&&f.mimeType!=='application/vnd.google-apps.folder')snap.drive.googleNative++;if(f.ownedByMe)snap.drive.owned++;else snap.drive.shared++;snap.drive.bytes+=Number(f.size??0);}pageToken=r.data.nextPageToken??undefined;}while(pageToken);}catch(e){errors.push({module:'drive',message:redact(e)});}
 try{const api=google.people({version:'v1',auth});let pageToken:string|undefined;do{const r=await api.people.connections.list({resourceName:'people/me',pageSize:1000,pageToken,personFields:'metadata'});snap.contacts.contacts+=(r.data.connections??[]).length;pageToken=r.data.nextPageToken??undefined;}while(pageToken);const groups=await api.contactGroups.list({pageSize:1000});snap.contacts.groups=groups.data.totalItems??(groups.data.contactGroups??[]).length;const other=await api.otherContacts.list({pageSize:1000,readMask:'metadata'});snap.contacts.otherContacts=other.data.totalSize??(other.data.otherContacts??[]).length;}catch(e){errors.push({module:'contacts',message:redact(e)});}
 try{const api=google.calendar({version:'v3',auth});let token:string|undefined;const ids:string[]=[];do{const r=await api.calendarList.list({maxResults:250,pageToken:token});for(const c of r.data.items??[]){if(!c.id)continue;ids.push(c.id);snap.calendar.calendars++;if(c.accessRole==='owner')snap.calendar.owned++;else snap.calendar.shared++;}token=r.data.nextPageToken??undefined;}while(token);for(const id of ids){let p:string|undefined;do{const r=await api.events.list({calendarId:id,maxResults:2500,pageToken:p,singleEvents:false,showDeleted:false});for(const e of r.data.items??[]){snap.calendar.events++;if(e.recurrence?.length)snap.calendar.recurring++;const start=e.start?.dateTime??e.start?.date;if(start&&new Date(start)>=new Date())snap.calendar.future++;}p=r.data.nextPageToken??undefined;}while(p);}}catch(e){errors.push({module:'calendar',message:redact(e)});}
 return snap;
}
